// AUTO-GENERATED by scripts/generate-asset-registry.mjs from assets-manifest.json.
// Do not edit by hand. Regenerate with: npm run assets:registry

import type { ImageAsset, MissingAsset, SoundAsset, VectorAsset } from './types';
import SvgQuestsFinalBattle from '../../../assets/quests/quest-final-battle.svg';
import SvgQuestsReading from '../../../assets/quests/quest-reading.svg';
import SvgQuestsReview from '../../../assets/quests/quest-review.svg';
import SvgQuestsVocabulary from '../../../assets/quests/quest-vocabulary.svg';
import SvgQuestsWeeklyExam from '../../../assets/quests/quest-weekly-exam.svg';

export const mascots = {
  /** assets/mascots/milo-achievement.webp · 1200×675 · VISUAL_REVIEW_REQUIRED */
  achievement: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-achievement.webp'),
    width: 1200,
    height: 675,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-champion.webp · 1200×675 · VISUAL_REVIEW_REQUIRED */
  champion: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-champion.webp'),
    width: 1200,
    height: 675,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-correct.webp · 768×702 · READY */
  correct: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-correct.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-day-complete.webp · 1200×1097 · VISUAL_REVIEW_REQUIRED */
  dayComplete: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-day-complete.webp'),
    width: 1200,
    height: 1097,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-deadline.webp · 1200×1097 · VISUAL_REVIEW_REQUIRED */
  deadline: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-deadline.webp'),
    width: 1200,
    height: 1097,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-exam.webp · 1200×675 · VISUAL_REVIEW_REQUIRED */
  exam: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-exam.webp'),
    width: 1200,
    height: 675,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-final-battle.webp · 1200×1097 · VISUAL_REVIEW_REQUIRED */
  finalBattle: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-final-battle.webp'),
    width: 1200,
    height: 1097,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-grammar.webp · 768×702 · READY */
  grammar: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-grammar.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-idle.webp · 768×702 · READY */
  idle: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-idle.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-learning.webp · 768×702 · READY */
  learning: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-learning.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-missed.webp · 1200×675 · VISUAL_REVIEW_REQUIRED */
  missed: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-missed.webp'),
    width: 1200,
    height: 675,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-perfect.webp · 1200×1097 · VISUAL_REVIEW_REQUIRED */
  perfect: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-perfect.webp'),
    width: 1200,
    height: 1097,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-reading.webp · 768×702 · READY */
  reading: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-reading.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-streak.webp · 1200×1200 · VISUAL_REVIEW_REQUIRED */
  streak: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-streak.webp'),
    width: 1200,
    height: 1200,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/mascots/milo-thinking.webp · 768×702 · READY */
  thinking: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-thinking.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-vocabulary.webp · 768×702 · READY */
  vocabulary: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-vocabulary.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-walking.webp · 768×702 · READY */
  walking: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-walking.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/mascots/milo-wrong.webp · 768×702 · READY */
  wrong: {
    kind: 'image',
    source: require('../../../assets/mascots/milo-wrong.webp'),
    width: 768,
    height: 702,
    hasAlpha: true,
    status: 'READY',
  },
} as const satisfies Record<string, ImageAsset>;

export const journey = {
  /** assets/journey/journey-background.webp · 1672×941 · READY */
  background: {
    kind: 'image',
    source: require('../../../assets/journey/journey-background.webp'),
    width: 1672,
    height: 941,
    hasAlpha: false,
    status: 'READY',
  },
  /** assets/journey/journey-camp.webp · 1200×800 · READY */
  camp: {
    kind: 'image',
    source: require('../../../assets/journey/journey-camp.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-campfire.webp · 1200×800 · READY */
  campfire: {
    kind: 'image',
    source: require('../../../assets/journey/journey-campfire.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-campfire-off.webp · 1200×800 · READY */
  campfireOff: {
    kind: 'image',
    source: require('../../../assets/journey/journey-campfire-off.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-flag.webp · 1200×800 · VISUAL_REVIEW_REQUIRED */
  flag: {
    kind: 'image',
    source: require('../../../assets/journey/journey-flag.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/journey/journey-forest.webp · 1200×800 · READY */
  forest: {
    kind: 'image',
    source: require('../../../assets/journey/journey-forest.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-mountains.webp · 1200×800 · READY */
  mountains: {
    kind: 'image',
    source: require('../../../assets/journey/journey-mountains.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-path.webp · 1156×1360 · READY */
  path: {
    kind: 'image',
    source: require('../../../assets/journey/journey-path.webp'),
    width: 1156,
    height: 1360,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-river.webp · 1200×800 · READY */
  river: {
    kind: 'image',
    source: require('../../../assets/journey/journey-river.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/journey/journey-summit.webp · 1200×800 · NEEDS_ALPHA_REVIEW */
  summit: {
    kind: 'image',
    source: require('../../../assets/journey/journey-summit.webp'),
    width: 1200,
    height: 800,
    hasAlpha: true,
    status: 'NEEDS_ALPHA_REVIEW',
  },
} as const satisfies Record<string, ImageAsset>;

export const chapters = {
  /** assets/chapters/chapter-01-beginning.webp · 1536×1024 · READY */
  beginning: {
    kind: 'image',
    source: require('../../../assets/chapters/chapter-01-beginning.webp'),
    width: 1536,
    height: 1024,
    hasAlpha: false,
    status: 'READY',
  },
  /** assets/chapters/chapter-02-momentum.webp · 1536×1024 · READY */
  momentum: {
    kind: 'image',
    source: require('../../../assets/chapters/chapter-02-momentum.webp'),
    width: 1536,
    height: 1024,
    hasAlpha: false,
    status: 'READY',
  },
  /** assets/chapters/chapter-03-habit.webp · 1536×1024 · READY */
  habit: {
    kind: 'image',
    source: require('../../../assets/chapters/chapter-03-habit.webp'),
    width: 1536,
    height: 1024,
    hasAlpha: false,
    status: 'READY',
  },
  /** assets/chapters/chapter-04-growth.webp · 1536×1024 · READY */
  growth: {
    kind: 'image',
    source: require('../../../assets/chapters/chapter-04-growth.webp'),
    width: 1536,
    height: 1024,
    hasAlpha: false,
    status: 'READY',
  },
  /** assets/chapters/chapter-05-summit.webp · 1536×1024 · READY */
  summit: {
    kind: 'image',
    source: require('../../../assets/chapters/chapter-05-summit.webp'),
    width: 1536,
    height: 1024,
    hasAlpha: false,
    status: 'READY',
  },
} as const satisfies Record<string, ImageAsset>;

export const badges = {
  /** assets/badges/badge-100-words.webp · 512×512 · READY */
  words100: {
    kind: 'image',
    source: require('../../../assets/badges/badge-100-words.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-14-days.webp · 512×512 · READY */
  days14: {
    kind: 'image',
    source: require('../../../assets/badges/badge-14-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-3-days.webp · 512×512 · READY */
  days3: {
    kind: 'image',
    source: require('../../../assets/badges/badge-3-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-30-days.webp · 512×512 · READY */
  days30: {
    kind: 'image',
    source: require('../../../assets/badges/badge-30-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-50-days.webp · 512×512 · READY */
  days50: {
    kind: 'image',
    source: require('../../../assets/badges/badge-50-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-500-words.webp · 512×512 · READY */
  words500: {
    kind: 'image',
    source: require('../../../assets/badges/badge-500-words.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-7-days.webp · 512×512 · READY */
  days7: {
    kind: 'image',
    source: require('../../../assets/badges/badge-7-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-90-days.webp · 512×512 · READY */
  days90: {
    kind: 'image',
    source: require('../../../assets/badges/badge-90-days.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-first-day.webp · 512×512 · READY */
  firstDay: {
    kind: 'image',
    source: require('../../../assets/badges/badge-first-day.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-perfect-quiz.webp · 512×512 · READY */
  perfectQuiz: {
    kind: 'image',
    source: require('../../../assets/badges/badge-perfect-quiz.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-perfect-week.webp · 512×512 · READY */
  perfectWeek: {
    kind: 'image',
    source: require('../../../assets/badges/badge-perfect-week.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/badges/badge-team-streak.webp · 512×512 · VISUAL_REVIEW_REQUIRED */
  teamStreak: {
    kind: 'image',
    source: require('../../../assets/badges/badge-team-streak.webp'),
    width: 512,
    height: 512,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
} as const satisfies Record<string, ImageAsset>;

export const quests = {
  /** assets/quests/quest-final-battle.svg · 96×96 · READY */
  finalBattle: {
    kind: 'vector',
    Component: SvgQuestsFinalBattle,
    width: 96,
    height: 96,
    status: 'READY',
  },
  /** assets/quests/quest-reading.svg · 96×96 · READY */
  reading: { kind: 'vector', Component: SvgQuestsReading, width: 96, height: 96, status: 'READY' },
  /** assets/quests/quest-review.svg · 96×96 · READY */
  review: { kind: 'vector', Component: SvgQuestsReview, width: 96, height: 96, status: 'READY' },
  /** assets/quests/quest-vocabulary.svg · 96×96 · VISUAL_REVIEW_REQUIRED */
  vocabulary: {
    kind: 'vector',
    Component: SvgQuestsVocabulary,
    width: 96,
    height: 96,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/quests/quest-weekly-exam.svg · 96×96 · READY */
  weeklyExam: {
    kind: 'vector',
    Component: SvgQuestsWeeklyExam,
    width: 96,
    height: 96,
    status: 'READY',
  },
} as const satisfies Record<string, VectorAsset>;

export const emptyStates = {
  /** assets/empty-states/no-friends-yet.webp · 768×640 · READY */
  noFriendsYet: {
    kind: 'image',
    source: require('../../../assets/empty-states/no-friends-yet.webp'),
    width: 768,
    height: 640,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/empty-states/no-internet.webp · 768×640 · READY */
  noInternet: {
    kind: 'image',
    source: require('../../../assets/empty-states/no-internet.webp'),
    width: 768,
    height: 640,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/empty-states/nothing-to-review.webp · 768×640 · READY */
  nothingToReview: {
    kind: 'image',
    source: require('../../../assets/empty-states/nothing-to-review.webp'),
    width: 768,
    height: 640,
    hasAlpha: true,
    status: 'READY',
  },
} as const satisfies Record<string, ImageAsset>;

export const effects = {
  /** assets/effects/confetti.webp · 1024×853 · READY */
  confetti: {
    kind: 'image',
    source: require('../../../assets/effects/confetti.webp'),
    width: 1024,
    height: 853,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/effects/perfect-rays.webp · 1024×853 · READY */
  perfectRays: {
    kind: 'image',
    source: require('../../../assets/effects/perfect-rays.webp'),
    width: 1024,
    height: 853,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/effects/sparkles.webp · 1024×853 · READY */
  sparkles: {
    kind: 'image',
    source: require('../../../assets/effects/sparkles.webp'),
    width: 1024,
    height: 853,
    hasAlpha: true,
    status: 'READY',
  },
  /** assets/effects/stars.webp · 1024×683 · VISUAL_REVIEW_REQUIRED */
  stars: {
    kind: 'image',
    source: require('../../../assets/effects/stars.webp'),
    width: 1024,
    height: 683,
    hasAlpha: true,
    status: 'VISUAL_REVIEW_REQUIRED',
  },
  /** assets/effects/streak-fire.webp · 768×640 · READY */
  streakFire: {
    kind: 'image',
    source: require('../../../assets/effects/streak-fire.webp'),
    width: 768,
    height: 640,
    hasAlpha: true,
    status: 'READY',
  },
} as const satisfies Record<string, ImageAsset>;

export const sounds = {
  /** assets/sounds/achievement-unlock.mp3 · READY */
  achievementUnlock: {
    kind: 'sound',
    source: require('../../../assets/sounds/achievement-unlock.mp3'),
    durationMs: 1063,
    status: 'READY',
  },
  /** assets/sounds/correct.mp3 · READY */
  correct: {
    kind: 'sound',
    source: require('../../../assets/sounds/correct.mp3'),
    durationMs: 159,
    status: 'READY',
  },
  /** assets/sounds/day-complete.mp3 · READY */
  dayComplete: {
    kind: 'sound',
    source: require('../../../assets/sounds/day-complete.mp3'),
    durationMs: 1300,
    status: 'READY',
  },
  /** assets/sounds/final-battle.mp3 · READY */
  finalBattle: {
    kind: 'sound',
    source: require('../../../assets/sounds/final-battle.mp3'),
    durationMs: 1765,
    status: 'READY',
  },
  /** assets/sounds/friend-joined.mp3 · READY */
  friendJoined: {
    kind: 'sound',
    source: require('../../../assets/sounds/friend-joined.mp3'),
    durationMs: 703,
    status: 'READY',
  },
  /** assets/sounds/level-up.mp3 · READY */
  levelUp: {
    kind: 'sound',
    source: require('../../../assets/sounds/level-up.mp3'),
    durationMs: 1393,
    status: 'READY',
  },
  /** assets/sounds/perfect.mp3 · READY */
  perfect: {
    kind: 'sound',
    source: require('../../../assets/sounds/perfect.mp3'),
    durationMs: 1207,
    status: 'READY',
  },
  /** assets/sounds/quest-complete.mp3 · READY */
  questComplete: {
    kind: 'sound',
    source: require('../../../assets/sounds/quest-complete.mp3'),
    durationMs: 350,
    status: 'READY',
  },
  /** assets/sounds/streak-lost.mp3 · READY */
  streakLost: {
    kind: 'sound',
    source: require('../../../assets/sounds/streak-lost.mp3'),
    durationMs: 929,
    status: 'READY',
  },
  /** assets/sounds/streak-up.mp3 · AUDIO_REVIEW_REQUIRED */
  streakUp: {
    kind: 'sound',
    source: require('../../../assets/sounds/streak-up.mp3'),
    durationMs: 743,
    status: 'AUDIO_REVIEW_REQUIRED',
  },
  /** assets/sounds/summit-victory.mp3 · READY */
  summitVictory: {
    kind: 'sound',
    source: require('../../../assets/sounds/summit-victory.mp3'),
    durationMs: 2508,
    status: 'READY',
  },
  /** assets/sounds/tap-soft.mp3 · AUDIO_REVIEW_REQUIRED */
  tapSoft: {
    kind: 'sound',
    source: require('../../../assets/sounds/tap-soft.mp3'),
    durationMs: 1000,
    status: 'AUDIO_REVIEW_REQUIRED',
  },
  /** assets/sounds/weekly-exam-pass.mp3 · READY */
  weeklyExamPass: {
    kind: 'sound',
    source: require('../../../assets/sounds/weekly-exam-pass.mp3'),
    durationMs: 1300,
    status: 'READY',
  },
  /** assets/sounds/weekly-exam-start.mp3 · READY */
  weeklyExamStart: {
    kind: 'sound',
    source: require('../../../assets/sounds/weekly-exam-start.mp3'),
    durationMs: 836,
    status: 'READY',
  },
  /** assets/sounds/wrong.mp3 · READY */
  wrong: {
    kind: 'sound',
    source: require('../../../assets/sounds/wrong.mp3'),
    durationMs: 557,
    status: 'READY',
  },
} as const satisfies Record<string, SoundAsset>;

/** Assets the app expects but that do not exist yet (see ASSET_MANIFEST.md). */
export const missingAssets = [
  { category: 'quests', expected: 'assets/quests/quest-grammar.svg' },
] as const satisfies readonly MissingAsset[];

export type MascotKey = keyof typeof mascots;
export type JourneyKey = keyof typeof journey;
export type ChapterKey = keyof typeof chapters;
export type BadgeKey = keyof typeof badges;
export type QuestKey = keyof typeof quests;
export type EmptyStateKey = keyof typeof emptyStates;
export type EffectKey = keyof typeof effects;
export type SoundKey = keyof typeof sounds;
