import type { WeeklyExam } from '@/schemas';

/**
 * Week 1 checkpoint (Day 7). It covers the days that are written so far —
 * Days 1 and 2 — and names the material each question tests, so the course
 * validator can prove it never asks about anything not taught yet.
 */
export const WEEK_01_EXAM: WeeklyExam = {
  type: 'weeklyExam',
  questId: 'd007-weeklyExam',
  id: 'exam-week-01',
  week: 1,
  day: 7,
  coveredDays: [1, 2],
  passingScore: 0.7,
  xpReward: 100,
  estimatedMinutes: 10,
  passages: [
    {
      id: 'lola-first-week',
      title: 'Lola’s First Week',
      text: 'Lola wants to speak English at work, so she starts a small routine. Every morning she learns five new words on the bus. In the evening she reads a short story and writes one sentence about her day. On Friday she makes a few mistakes in a meeting, but her colleague says her English is getting better. Lola smiles: small steps are working.',
    },
  ],
  questions: [
    {
      id: 'w01-v1',
      section: 'vocabulary',
      kind: 'meaning',
      sourceDay: 1,
      prompt: 'What does “goal” mean?',
      options: [
        { id: 'a', text: 'путешествие' },
        { id: 'b', text: 'цель' },
        { id: 'c', text: 'привычка' },
        { id: 'd', text: 'распорядок дня' },
      ],
      correctOptionId: 'b',
      explanation: 'A goal — цель: something you want to achieve.',
      materialIds: ['vocab-goal'],
    },
    {
      id: 'w01-v2',
      section: 'vocabulary',
      kind: 'meaning',
      sourceDay: 2,
      prompt: 'How do you say “обычно” in English?',
      options: [
        { id: 'a', text: 'usually' },
        { id: 'b', text: 'together' },
        { id: 'c', text: 'quiet' },
        { id: 'd', text: 'early' },
      ],
      correctOptionId: 'a',
      explanation: 'Usually — обычно: in most cases, most of the time.',
      materialIds: ['vocab-usually'],
    },
    {
      id: 'w01-v3',
      section: 'vocabulary',
      kind: 'sentenceCompletion',
      sourceDay: 1,
      prompt: 'Choose the word that fits.',
      sentence: 'I drink water as soon as I wake up — it is a ___ now.',
      options: [
        { id: 'a', text: 'journey' },
        { id: 'b', text: 'goal' },
        { id: 'c', text: 'habit' },
        { id: 'd', text: 'practice' },
      ],
      correctOptionId: 'c',
      explanation: 'A habit is something you do regularly, often without thinking.',
      materialIds: ['vocab-habit'],
    },
    {
      id: 'w01-v4',
      section: 'vocabulary',
      kind: 'context',
      sourceDay: 2,
      prompt: '“The camp is quiet in the morning.” What does “quiet” mean here?',
      options: [
        { id: 'a', text: 'тихий' },
        { id: 'b', text: 'холодный' },
        { id: 'c', text: 'пустой' },
        { id: 'd', text: 'красивый' },
      ],
      correctOptionId: 'a',
      explanation: 'Quiet — тихий: making very little noise.',
      materialIds: ['vocab-quiet'],
    },
    {
      id: 'w01-g1',
      section: 'grammar',
      kind: 'correctForm',
      sourceDay: 1,
      prompt: 'Choose the right form.',
      sentence: 'Our teacher ___ in a small village.',
      options: [
        { id: 'a', text: 'live' },
        { id: 'b', text: 'lives' },
        { id: 'c', text: 'living' },
      ],
      correctOptionId: 'b',
      explanation: 'He / she takes -s in Present Simple: lives.',
      materialIds: ['grammar-present-simple-habits.third-person'],
    },
    {
      id: 'w01-g2',
      section: 'grammar',
      kind: 'correctForm',
      sourceDay: 2,
      prompt: 'Choose the right form.',
      sentence: 'He ___ TV only on Sundays.',
      options: [
        { id: 'a', text: 'watchs' },
        { id: 'b', text: 'watches' },
        { id: 'c', text: 'watchies' },
      ],
      correctOptionId: 'b',
      explanation: 'Watch ends in -ch, so it takes -es: watches.',
      materialIds: ['grammar-present-simple-spelling.es'],
    },
    {
      id: 'w01-g3',
      section: 'grammar',
      kind: 'sentenceCorrectness',
      sourceDay: 2,
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'She studys every evening.' },
        { id: 'b', text: 'She studies every evening.' },
        { id: 'c', text: 'She studyes every evening.' },
      ],
      correctOptionId: 'b',
      explanation: 'Consonant + y: the y becomes -ies — studies.',
      materialIds: ['grammar-present-simple-spelling.ies'],
    },
    {
      id: 'w01-r1',
      section: 'reading',
      kind: 'readingComprehension',
      sourceDay: 2,
      prompt: 'What is the text mainly about?',
      passageId: 'lola-first-week',
      options: [
        { id: 'a', text: 'A small daily routine helps Lola’s English.' },
        { id: 'b', text: 'Lola changes her job.' },
        { id: 'c', text: 'Lola writes a story for her company.' },
      ],
      correctOptionId: 'a',
      explanation: 'She learns words every morning and reads every evening — and it works.',
    },
    {
      id: 'w01-r2',
      section: 'reading',
      kind: 'inference',
      sourceDay: 2,
      prompt: 'How does Lola feel at the end?',
      passageId: 'lola-first-week',
      options: [
        { id: 'a', text: 'Tired, and ready to stop.' },
        { id: 'b', text: 'Happy that small steps work.' },
        { id: 'c', text: 'Angry with her colleague.' },
      ],
      correctOptionId: 'b',
      explanation: '“Lola smiles: small steps are working.”',
    },
  ],
};
